---
http_interactions:
- request:
    method: post
    uri: "<API_ENDPOINT>/api/3/contacts"
    body:
      encoding: UTF-8
      string: '{"contact":{"email":"anmolyousaf94@gmail.com","firstName":"Anmol","lastName":"Yousaf","phone":"+491735728523"}}'
    headers:
      Api-Token:
      - "<API_KEY>"
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Wed, 24 Mar 2021 08:13:19 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '2050'
      Connection:
      - keep-alive
      Set-Cookie:
      - PHPSESSID=8a2722c052011a0d745950612a3f3890; path=/; HttpOnly
      - __cfduid=d9261b81726f2e727d3ebff49fccfa9681616573598; expires=Fri, 23-Apr-21
        08:13:18 GMT; path=/; domain=.api-us1.com; HttpOnly; SameSite=Lax
      - em_acp_globalauth_cookie=7426e8c0-d36f-435e-8d84-cadc8233bdf6; path=/; domain=.wegohealth1616524231.api-us1.com;
        secure; httponly
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      Access-Control-Allow-Headers:
      - Content-Type, origin, x-requested-with
      Access-Control-Allow-Methods:
      - POST, GET
      Access-Control-Allow-Origin:
      - "*"
      Cache-Control:
      - no-store, no-cache, must-revalidate
      Expires:
      - Thu, 19 Nov 1981 08:52:00 GMT
      Pragma:
      - no-cache
      X-Content-Type-Options:
      - nosniff
      X-Envoy-Upstream-Service-Time:
      - '276'
      X-Request-Id:
      - c92ac932-9c4b-4085-9ede-646f6f8c05c5
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Request-Id:
      - '0904e4a3de000014dd680f2000000001'
      Expect-Ct:
      - max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
      Server:
      - cloudflare
      Cf-Ray:
      - 634e707fce4014dd-DXB
    body:
      encoding: UTF-8
      string: '{"contact":{"email":"anmolyousaf94@gmail.com","phone":"+491735728523","firstName":"Anmol","lastName":"Yousaf","email_empty":false,"cdate":"2021-03-24T03:13:19-05:00","udate":"2021-03-24T03:13:19-05:00","orgid":"","orgname":"","links":{"bounceLogs":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/bounceLogs","contactAutomations":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/contactAutomations?limit=1000&orders%5Blastdate%5D=DESC","contactData":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/contactData","contactGoals":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/contactGoals","contactLists":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/contactLists","contactLogs":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/contactLogs","contactTags":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/contactTags","contactDeals":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/contactDeals","deals":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/deals","fieldValues":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/fieldValues","geoIps":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/geoIps","notes":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/notes","organization":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/organization","plusAppend":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/plusAppend","trackingLogs":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/trackingLogs","scoreValues":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/scoreValues","accountContacts":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/accountContacts","automationEntryCounts":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/automationEntryCounts"},"hash":"7ba1befd8ad189aad87b2d49876aae5e","id":"46","organization":""}}'
  recorded_at: Wed, 24 Mar 2021 08:13:19 GMT
- request:
    method: post
    uri: "<API_ENDPOINT>/api/3/fields"
    body:
      encoding: UTF-8
      string: '{"field":{"title":"Custom text","type":"text","descript":"A custom
        text field","isrequired":"0","perstag":"PERSTAG","defval":"Default value","visible":"1"}}'
    headers:
      Api-Token:
      - "<API_KEY>"
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Wed, 24 Mar 2021 08:13:21 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '467'
      Connection:
      - keep-alive
      Set-Cookie:
      - PHPSESSID=6b0e96efcaf7d0d7f9ffee40b6151dc6; path=/; HttpOnly
      - __cfduid=d2ee77bb4ecc6944fe084fb471401a4841616573599; expires=Fri, 23-Apr-21
        08:13:19 GMT; path=/; domain=.api-us1.com; HttpOnly; SameSite=Lax
      - em_acp_globalauth_cookie=5d94d24c-12cf-4492-8b21-a3b233fa8843; path=/; domain=.wegohealth1616524231.api-us1.com;
        secure; httponly
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      Cache-Control:
      - no-store, no-cache, must-revalidate
      Expires:
      - Thu, 19 Nov 1981 08:52:00 GMT
      Pragma:
      - no-cache
      X-Envoy-Upstream-Service-Time:
      - '573'
      X-Request-Id:
      - 2fc45d62-19c1-46da-a13e-1ce143a3fafe
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Request-Id:
      - '0904e4a74a000012bec4966000000001'
      Expect-Ct:
      - max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
      Server:
      - cloudflare
      Cf-Ray:
      - 634e7085398212be-DXB
    body:
      encoding: UTF-8
      string: '{"field":{"title":"Custom text","type":"text","descript":"A custom
        text field","isrequired":"0","perstag":"PERSTAG","defval":"Default value","visible":"1","created_by":"1","updated_by":"1","cdate":"2021-03-24T03:13:19-05:00","udate":"2021-03-24T03:13:19-05:00","ordernum":1,"links":{"options":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/fields\/55\/options","relations":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/fields\/55\/relations"},"id":"55"}}'
  recorded_at: Wed, 24 Mar 2021 08:13:21 GMT
- request:
    method: post
    uri: "<API_ENDPOINT>/api/3/fieldValues"
    body:
      encoding: UTF-8
      string: '{"fieldValue":{"contact":"46","field":"55","value":"Text field value"},"useDefaults":false}'
    headers:
      Api-Token:
      - "<API_KEY>"
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Wed, 24 Mar 2021 08:13:22 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '2896'
      Connection:
      - keep-alive
      Set-Cookie:
      - PHPSESSID=f00b97ca1014e3f9ee8a219ace6ecd39; path=/; HttpOnly
      - __cfduid=df6d8f302e0f0e8f3cce070f0a51c87481616573601; expires=Fri, 23-Apr-21
        08:13:21 GMT; path=/; domain=.api-us1.com; HttpOnly; SameSite=Lax
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=f458d677-c54d-4543-8cbe-f9f55b93827b; path=/; domain=.wegohealth1616524231.api-us1.com;
        secure; httponly
      Cache-Control:
      - no-store, no-cache, must-revalidate
      Expires:
      - Thu, 19 Nov 1981 08:52:00 GMT
      Pragma:
      - no-cache
      X-Envoy-Upstream-Service-Time:
      - '168'
      X-Request-Id:
      - 1682f98b-47b1-4d4a-becb-e571c645f428
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Request-Id:
      - '0904e4b053000014e5ea089000000001'
      Expect-Ct:
      - max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
      Server:
      - cloudflare
      Cf-Ray:
      - 634e7093bb1114e5-DXB
    body:
      encoding: UTF-8
      string: '{"contacts":[{"cdate":"2021-03-24T03:13:19-05:00","email":"anmolyousaf94@gmail.com","phone":"+491735728523","firstName":"Anmol","lastName":"Yousaf","orgid":"0","orgname":"","segmentio_id":"","bounced_hard":"0","bounced_soft":"0","bounced_date":null,"ip":"0","ua":null,"hash":"7ba1befd8ad189aad87b2d49876aae5e","socialdata_lastcheck":null,"email_local":"","email_domain":"","sentcnt":"0","rating_tstamp":null,"gravatar":"0","deleted":"0","anonymized":"0","adate":null,"udate":"2021-03-24T03:13:22-05:00","edate":null,"deleted_at":null,"created_utc_timestamp":"2021-03-24
        03:13:19","updated_utc_timestamp":"2021-03-24 03:13:22","created_timestamp":"2021-03-24
        03:13:19","updated_timestamp":"2021-03-24 03:13:22","created_by":null,"updated_by":null,"email_empty":false,"links":{"bounceLogs":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/bounceLogs","contactAutomations":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/contactAutomations?limit=1000&orders%5Blastdate%5D=DESC","contactData":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/contactData","contactGoals":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/contactGoals","contactLists":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/contactLists","contactLogs":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/contactLogs","contactTags":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/contactTags","contactDeals":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/contactDeals","deals":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/deals","fieldValues":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/fieldValues","geoIps":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/geoIps","notes":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/notes","organization":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/organization","plusAppend":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/plusAppend","trackingLogs":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/trackingLogs","scoreValues":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/scoreValues","accountContacts":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/accountContacts","automationEntryCounts":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/contacts\/46\/automationEntryCounts"},"id":"46","organization":null}],"fieldValue":{"contact":"46","field":"55","value":"Text
        field value","cdate":"2021-03-24T03:13:22-05:00","udate":"2021-03-24T03:13:22-05:00","links":{"owner":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/fieldValues\/29\/owner","field":"https:\/\/wegohealth1616524231.api-us1.com\/api\/3\/fieldValues\/29\/field"},"owner":"46","id":"29"}}'
  recorded_at: Wed, 24 Mar 2021 08:13:22 GMT
- request:
    method: get
    uri: "<API_ENDPOINT>/api/3/fieldValues?filters%5Bval%5D=non-existing"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Api-Token:
      - "<API_KEY>"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 24 Mar 2021 08:13:24 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '39'
      Connection:
      - keep-alive
      Set-Cookie:
      - PHPSESSID=8175236994d026158c4e72909594ac06; path=/; HttpOnly
      - __cfduid=d48c886c70308c288d6377f2742b3917b1616573602; expires=Fri, 23-Apr-21
        08:13:22 GMT; path=/; domain=.api-us1.com; HttpOnly; SameSite=Lax
      - em_acp_globalauth_cookie=92b7b507-fc84-410c-a032-ed3031065213; path=/; domain=.wegohealth1616524231.api-us1.com;
        secure; httponly
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      Cache-Control:
      - no-store, no-cache, must-revalidate
      Expires:
      - Thu, 19 Nov 1981 08:52:00 GMT
      Pragma:
      - no-cache
      X-Envoy-Upstream-Service-Time:
      - '114'
      X-Request-Id:
      - e922acd0-3eb8-4fe1-9793-3a8d6c3c618c
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Request-Id:
      - '0904e4b284000014e5f4967000000001'
      Expect-Ct:
      - max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
      Server:
      - cloudflare
      Cf-Ray:
      - 634e709738a114e5-DXB
    body:
      encoding: UTF-8
      string: '{"fieldValues":[],"meta":{"total":"0"}}'
  recorded_at: Wed, 24 Mar 2021 08:13:23 GMT
- request:
    method: delete
    uri: "<API_ENDPOINT>/api/3/fieldValues/29"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Api-Token:
      - "<API_KEY>"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 24 Mar 2021 08:13:25 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '2'
      Connection:
      - keep-alive
      Set-Cookie:
      - PHPSESSID=1a6c6688f213f212d2ad8240b122b66e; path=/; HttpOnly
      - __cfduid=d419e77bf604a78c82ed3ffbf2a2900311616573604; expires=Fri, 23-Apr-21
        08:13:24 GMT; path=/; domain=.api-us1.com; HttpOnly; SameSite=Lax
      - em_acp_globalauth_cookie=2e5b46da-3855-454e-b19d-c09fc9b161c2; path=/; domain=.wegohealth1616524231.api-us1.com;
        secure; httponly
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      Cache-Control:
      - no-store, no-cache, must-revalidate
      Expires:
      - Thu, 19 Nov 1981 08:52:00 GMT
      Pragma:
      - no-cache
      X-Envoy-Upstream-Service-Time:
      - '133'
      X-Request-Id:
      - 6f196f38-b5e5-4705-a9ff-f7ecea7d8387
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Request-Id:
      - '0904e4b953000012c27a8eb000000001'
      Expect-Ct:
      - max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
      Server:
      - cloudflare
      Cf-Ray:
      - 634e70a21e2c12c2-DXB
    body:
      encoding: UTF-8
      string: "{}"
  recorded_at: Wed, 24 Mar 2021 08:13:25 GMT
- request:
    method: delete
    uri: "<API_ENDPOINT>/api/3/fields/55"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Api-Token:
      - "<API_KEY>"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 24 Mar 2021 08:13:30 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '2'
      Connection:
      - keep-alive
      Set-Cookie:
      - PHPSESSID=510e5f4a3384d990ef4b107530e4b392; path=/; HttpOnly
      - __cfduid=d55b264a67ec52589d97e221c00d301fc1616573606; expires=Fri, 23-Apr-21
        08:13:26 GMT; path=/; domain=.api-us1.com; HttpOnly; SameSite=Lax
      - em_acp_globalauth_cookie=a6609537-40bc-437f-a973-c641994e6bdc; path=/; domain=.wegohealth1616524231.api-us1.com;
        secure; httponly
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      Cache-Control:
      - no-store, no-cache, must-revalidate
      Expires:
      - Thu, 19 Nov 1981 08:52:00 GMT
      Pragma:
      - no-cache
      X-Envoy-Upstream-Service-Time:
      - '281'
      X-Request-Id:
      - e799ce8a-7a38-4eda-9307-ef70ac3c6a86
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Request-Id:
      - '0904e4c0a5000014d9873f7000000001'
      Expect-Ct:
      - max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
      Server:
      - cloudflare
      Cf-Ray:
      - 634e70addede14d9-DXB
    body:
      encoding: UTF-8
      string: "{}"
  recorded_at: Wed, 24 Mar 2021 08:13:30 GMT
- request:
    method: delete
    uri: "<API_ENDPOINT>/api/3/contacts/46"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Api-Token:
      - "<API_KEY>"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 24 Mar 2021 08:13:31 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '2'
      Connection:
      - keep-alive
      Set-Cookie:
      - PHPSESSID=b83306a6fe31a6fb8058811c3960c7be; path=/; HttpOnly
      - __cfduid=da20575ee752bbfdb6ab93e6d5bf2db7e1616573610; expires=Fri, 23-Apr-21
        08:13:30 GMT; path=/; domain=.api-us1.com; HttpOnly; SameSite=Lax
      - em_acp_globalauth_cookie=9f0a2f32-6e2a-430e-93a6-46c64c1b2398; path=/; domain=.wegohealth1616524231.api-us1.com;
        secure; httponly
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      - em_acp_globalauth_cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
        path=/; domain=.wegohealth1616524231.api-us1.com
      Cache-Control:
      - no-store, no-cache, must-revalidate
      Expires:
      - Thu, 19 Nov 1981 08:52:00 GMT
      Pragma:
      - no-cache
      X-Envoy-Upstream-Service-Time:
      - '193'
      X-Request-Id:
      - 113c5467-4a50-412e-86f2-fb0578a58706
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Request-Id:
      - '0904e4d310000014dd55325000000001'
      Expect-Ct:
      - max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
      Server:
      - cloudflare
      Cf-Ray:
      - 634e70cb49e814dd-DXB
    body:
      encoding: UTF-8
      string: "{}"
  recorded_at: Wed, 24 Mar 2021 08:13:31 GMT
recorded_with: VCR 6.0.0
